version: '4.12'
services:
    blog-nginx:
        container_name: blog-nginx
        restart: "no"
        build:
            context: ./
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./:/var/www
            - ./docker/nginx/${VHOST_FILE}:/etc/nginx/conf.d/custom.conf
        ports:
            - "80"
        links:
            - blog-php
        environment:
            VIRTUAL_HOST: ${DOMAIN_HOST}
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: ${DOMAIN_HOST}
            LETSENCRYPT_EMAIL: ${DOMAIN_EMAIL}
        networks:
            - nginx-proxy
            - blog
    blog-php:
        container_name: blog-php
        restart: "no"
        user: ${USER_ID}:${GROUP_ID}
        build:
            context: ./
            dockerfile: docker/php/Dockerfile
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./docker/php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        links:
            - blog-mysql
            - blog-redis
        ports:
            - "9001:9003"
        tmpfs:
            - /dev/shm
        extra_hosts:
            - "hosts.docker.internal:host-gateway"
        networks:
            - blog

    blog-mysql:
        container_name: blog-mysql
        image: mysql:8.0.31
        restart: "no"
        volumes:
            - ./docker/mysql/myconf.conf:/etc/mysql/conf.d/myconf.conf
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - ${MYSQL_EXTERNAL_PORT}:3306
        networks:
            - blog


    blog-redis:
        container_name: blog-redis
        restart: "no"
        build:
            context: ./
            dockerfile: docker/redis/Dockerfile
            args:
                REDIS_PASSWORD: ${REDIS_PASSWORD}
        ports:
            -   ${REDIS_EXTERNAL_PORT}:6379
        sysctls:
            - net.core.somaxconn=511
        networks:
            - blog


networks:
    blog:

    nginx-proxy:
        external: true
